config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources         :championships do
    resources :weeks
  end

  resources :weeks, only: [] do
    resources :matches
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "dashboard"  => "dashboard#index"
  get "dashboard_search" => "dashboard#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/championship.rb
class Championship < ApplicationRecord
    # Validations
    validates_presence_of :city, :name, :start_date, :end_date

    # Relationships
    has_many        :weeks
    has_many        :matches, through: :weeks

    accepts_nested_attributes_for :weeks
end

app/models/match.rb
class Match < ApplicationRecord
    belongs_to      :week
    has_one         :championship, through: :week
    belongs_to      :local, class_name: "Team"
    belongs_to      :visitor, class_name: "Team"
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to      :team
    belongs_to      :user
end

app/models/team.rb
class Team < ApplicationRecord
    has_many        :players
    has_many        :local_matches, class_name: "Match", foreign_key: "local_id"
    has_many        :visitor_matches, class_name: "Match", foreign_key: "visitor_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/week.rb
class Week < ApplicationRecord
    validates_presence_of       :name, :date

    belongs_to      :championship
    has_many        :matches
    accepts_nested_attributes_for       :matches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(user)
        dashboard_path
    end
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
    before_action       :authenticate_user!
    def new
        @championship = Championship.new
    end

    def create
        c = Championship.create(championship_params)
        if c.persisted?
            redirect_to dashboard_path(), notice: 'El campeonato fue creado exitosamente'
        else
            render :new, alert: 'El campeonato no pudo ser creado'
        end
    end

    def show
        @championship = Championship.find(params[:id])
    end

    def edit
        @championship = Championship.find(params[:id])
    end

    def update
        @championship = Championship.find(params[:id])
        if @championship.update(championship_params)
            redirect_to dashboard_path(), notice: 'El campeonato fue actualizado exitosamente'
        else
            render :edit, alert: 'El campeonato no pudo ser actualizado'
        end
    end

    def destroy
        championship = Championship.find(params[:id])
        if championship.destroy
            redirect_to dashboard_path(), notice: 'El campeonato fue eliminado exitosamente'
        else
            redirect_to dashboard_path(), notice: 'El campeonato no pudo ser eliminado'
        end
    end

    private
    def championship_params
        params.require(:championship).permit(:city, :name, :start_date, :end_date, weeks_attributes: [:name, :date, :_destroy])
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
        @championships = Championship.all
        @current_championship = Championship.first
        @current_week = @current_championship.weeks.order(:date).first
        @current_match = @current_week.matches.order(:date).first
    end

    def search
        @championships = Championship.all
        if params[:championship_id].present?
            @current_championship = Championship.find(params[:championship_id])
            @current_week = @current_championship.weeks.order(:date).first
            @current_match = @current_week.matches.order(:date).first
        elsif params[:week_id].present?
            @current_week = Week.find(params[:week_id])
            @current_championship = @current_week.championship
            @current_match = @current_week.matches.order(:date).first
        else
            @current_match = Match.find(params[:match_id])
            @current_week = @current_match.week
            @current_championship = @current_match.championship
        end
        respond_to do |format|
            format.js
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
    before_action       :authenticate_user!
    def index
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    before_action       :authenticate_user!

    def new
        @week = Week.find(params[:week_id])
        @match = Match.new
        @teams = Team.all()
    end

    def create

        m = Match.create(match_params)

        if m.persisted?
            redirect_to dashboard_path(), notice: 'El partido fue creado exitosamente'
        else
            @week = Week.find(params[:week_id])
            @match = Match.new
            @teams = Team.all()
            render :new, alert: 'El partido no pudo ser creado'
        end
    end

    private
    def match_params
        params.require(:match).permit(:local_id, :visitor_id, :week_id)
    end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
    before_action       :authenticate_user!

    def new
        @championship = Championship.find(params[:championship_id])
        @week = Week.new championship_id: params[:championship_id]
        @teams = Team.all()
    end

    def create
        week = Week.create(week_params)
        if week.persisted?
            redirect_to dashbard_path(), notice: 'Fecha exitosamente creada'
        else
            render :new, alert: 'Fecha no fue creada exitosamente. #{week.errors.full_messages}'
        end
    end

    private
    def week_params
        params.require(:week).permit(:name, :date, :championship_id, matches_attributes: [:local_id, :visitor_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/championships/_form.html.haml
= simple_form_for @championship do |f|
  = f.input   :name, wrapper_html: {class: 'input-field'}
  = f.input   :city, wrapper_html: {class: 'input-field'}
  = f.input   :start_date, as: :string, input_html: {class: 'datepicker'}, wrapper_html: {class: 'input-field'}
  = f.input   :end_date, as: :string, input_html: {class: 'datepicker'}, wrapper_html: {class: 'input-field'}
  %h5 Fechas
  #weeks
    = f.simple_fields_for :weeks do |week|
      = render 'week_fields', f: week
    .links
      = link_to_add_association 'Añadir fecha', f, :weeks

  = f.button  :submit, class: 'btn btn-primary'


= link_to "Regresar",  dashboard_path()

:javascript
  M.AutoInit();

app/views/championships/_week_fields.html.haml
.nested-fields.row
  .col.m5
    = f.input     :name, wrapper_html: {class: 'input-field'}
  .col.m5
    = f.input     :date, as: :string, wrapper_html: {class: 'input-field'}, input_html: {class: 'datepicker'}
  .col.m2
    = link_to_remove_association "Quitar fecha", f

  :javascript
    M.AutoInit()

app/views/championships/edit.html.haml
%h4 Editar campeoanto

= render partial: "form"

app/views/championships/new.html.haml
.container
  %h5 Crear torneo
  = render partial: "form"

app/views/championships/show.html.haml
%h4= "Detalles del campeonato #{@championship.name}"
%p Fechas

app/views/dashboard/_sidenav.html.haml
%ul.sidenav.sidenav-fixed
  %li.bold{style: "padding: 0 32px;"}
    %h4 MiTorneo
  .content-sidebar{style: "height: 91%;"}
    .sidebar-element-container{style: "height: 33%;"}
      %li.bold{style: "padding: 0 32px;"} Torneos
      - championships.each do |championship|
        %li{class: current_championship == championship ? 'bold active': 'bold'}
          = link_to "#{championship.name}", dashboard_search_path(championship_id: championship.id), remote: true
      %li.bold
        = link_to "Crear torneo...", new_championship_path()
    .sidebar-element-container{style: "height: 33%;"}
      %li.bold{style: "padding: 0 32px;"} Fechas
      - current_championship.weeks.order(:date).each do |week|
        %li{class: @current_week == week ? 'bold active': 'bold'}
          = link_to "#{week.name}", dashboard_search_path(week_id: week.id), remote: true
      %li.bold
        = link_to "Agregar fecha a este campeonato...", new_championship_week_path(championship_id: current_championship.id)
    .sidebar-element-container{style: "height: 33%;"}
      %li.bold{style: "padding: 0 32px;"} Partidos
      - current_week.matches.order(:date).each do |match|
        %li{class: @current_match == match ? 'bold active': 'bold'}
          = link_to "#{match.local.short_name} - #{match.visitor.short_name}", dashboard_search_path(match_id: match.id), remote: true
      %li.bold
        = link_to "Crear partidos para esta fecha...", new_week_match_path(week_id: current_week)

app/views/dashboard/index.html.haml
/ Navbar goes here
/ Page Layout here
#dashboard_sidenav
  = render partial: "sidenav", locals: {championships: @championships, current_championship: @current_championship, current_week: @current_week, current_match: @current_match}

%main.content-with-sidenav
  .container-with-sidenav#match_summary
    = render partial: "matches/summary", locals: {match: @current_match}

app/views/dashboard/search.js.erb
$('#dashboard_sidenav').html(`<%= raw render partial: 'dashboard/sidenav', locals: {championships: @championships, current_championship: @current_championship, current_week: @current_week, current_match: @current_match} %>`);
$('#match_summary').html(`<%= raw render partial: "matches/summary", locals: {match: @current_match} %>`);

app/views/home/index.html.haml
%h3 Bienvenido a Mi torneo
%p Aquí podras consultar los resultados de tus partidos en los torneos que juegas
- if user_signed_in?
  = link_to "Cerrar sesión", destroy_user_session_path, method: :delete
- else
  = link_to "Iniciar sesión", new_user_session_path

app/views/inscriptions/_form.html.haml
= simple_form_for @championship do |f|
  = f.input   :name
  = f.input   :city
  .input-field
    = f.input   :start_date, as: :date
  .input-field
    = f.input   :end_date, as: :date
  = f.button  :submit

:javascript
  M.AutoInit();

app/views/inscriptions/edit.html.haml
%h4 Editar campeoanto

= render partial: "form"

app/views/inscriptions/index.html.haml
-#%a= "#{current_user.email}"
%nav
  .nav-wrapper
    %a.brand-logo{:href => "#"} MI TORNEO

    %ul#nav-mobile.right.hide-on-med-and-down
      %li
        %a{:href => "sass.html"} INICIO
      %li
        %a{:href => "badges.html"} INSCRIPCIONES
      %li
        %a{:href => "collapsible.html"} TARJETAS
      %li
        %a{:href => "collapsible.html"} PLANILLAS
      %li
        %a{:href => "collapsible.html"} ARCHIVOS
      / Dropdown Trigger
      %a.dropdown-trigger.btn{"data-target" => "dropdown1", :href => "#"} TABLAS
      / Dropdown Structure
      %ul#dropdown1.dropdown-content
        %li
          %a{:href => "#!"} one
        %li
          %a{:href => "#!"} two
        %li.divider{:tabindex => "-1"}
        %li
          %a{:href => "#!"} three
        %li
          %a{:href => "#!"}
            %i.material-icons> view_module
            four
        %li
          %a{:href => "#!"}
            %i.material-icons> cloud
            five


/ Navbar goes here
/ Page Layout here
.row
  .col.s12.m4.l3
    .col.s12
      %h5="TORNEOS"



    .col.s12
      %h5="TORNEO EQUIPOS"
  .col.s12.m4.l3
    .col.s12
      %center
        %h5="AGREGUE JUGADORES"
        %h5="NAME OF TEAM"
  .col.s12.m4.l3
    .col.s12
      %center
        %h5="JUGADORES"

app/views/inscriptions/new.html.haml
%h5 Crear campeonato
= render partial: "form"

app/views/inscriptions/show.html.haml
%h4= "Detalles del campeonato #{@championship.name}"
%p Fechas

app/views/layouts/_navbar.html.haml
%nav
  .nav-wrapper
    %a.brand-logo{:href => "#"} MI TORNEO

    %ul#nav-mobile.right.hide-on-med-and-down
      %li
        = link_to "INICIO", dashboard_path()
      %li
        %a{:href => "inscriptions"} INSCRIPCIONES
      %li
        %a{:href => "collapsible.html"} TARJETAS
      %li
        %a{:href => "collapsible.html"} PLANILLAS
      %li
        %a{:href => "collapsible.html"} ARCHIVOS
      / Dropdown Trigger
      %a.dropdown-trigger.btn{"data-target" => "dropdown1", :href => "#"} TABLAS
      / Dropdown Structure
      %ul#dropdown1.dropdown-content
        %li
          %a{:href => "#!"} one
        %li
          %a{:href => "#!"} two
        %li.divider{:tabindex => "-1"}
        %li
          %a{:href => "#!"} three
        %li
          %a{:href => "#!"}
            %i.material-icons> view_module
            four
        %li
          %a{:href => "#!"}
            %i.material-icons> cloud
            five

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mitorneo
    = csrf_meta_tags
    = csp_meta_tag
    %script{:crossorigin => "anonymous", :integrity => "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=", :src => "https://code.jquery.com/jquery-3.3.1.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    - if flash[:notice]
      %h4= flash[:notice]
    - if flash[:alert]
      %h4= flash[:alert]
    - if user_signed_in?
      = render partial: "layouts/navbar"
    = yield

app/views/matches/_form.html.haml
= simple_form_for [@week, @match] do |f|
  %h5 Partidos
  .nested-fields.row
  .col.m5
    = f.input     :local_id, as: :select, collection: @teams.map{|team| ["#{team.name} (#{team.short_name})", team.id]}, wrapper_html: {class: 'input-field'}, include_blank: false
  %center
    %span VS
  .col.m5
    = f.input     :visitor_id, as: :select, collection: @teams.map{|team| ["#{team.name} (#{team.short_name})", team.id]}, wrapper_html: {class: 'input-field'}, include_blank: false
  .col.m2
    = f.input :week_id, as: :hidden, input_html: {value: @week.id}

  = f.button  :submit, class: 'btn btn-primary'

:javascript
  M.AutoInit();

app/views/matches/_summary.html.haml
- if match.nil?
  %p No se ha seleccionado un partido
- else
  .row
    %h5="Detalles partido #{match.local.name} - #{match.visitor.name}"
    %hr
    .row
      .col.s12
        %h5= "RESULTADO"
        %form{:action => "#"}
          %p
            %label
              %input{:checked => "checked", :name => "group1", :type => "radio"}/
              %span LOC
              %input{:checked => "checked", :name => "group1", :type => "radio"}/
              %span VIS
              %input{:checked => "checked", :name => "group1", :type => "radio"}/
              %span EMP4

          %a.waves-effect.waves-light.btn SUBIR FOTO PLANILLA

    %hr
    .row
      .col.s4
        %h5= "Local: #{match.local.name}"
        %form{:action => "#"}
          - (0..9).each do |element|
            %p
              %label
                %input.filled-in{ :type => "checkbox"}/
                %span= "#{element+1} Jugador #####{element+1}"
      .col.s4
        %h5= "Visitante: #{match.visitor.name}"
        %form{:action => "#"}
          - (0..9).each do |element|
            %p
              %label
                %input.filled-in{ :type => "checkbox"}/
                %span= "#{element+1} Jugador #####{element+1}"


      .col.s4

        .col.s12
          %h5= "EDICIÓN POR LOTE"
        .col.s12
          %h5= "GOLES"
          %input#last_name.validate{:placeholder => "2", :type => "text"}/
          %center
            %a.waves-effect.waves-light.btn-large Agregar
        .col.s12

          %h5= "TARJETAS"
          %select
            %option{:disabled => "disabled", :selected => "selected", :value => ""} Selecciona tu opción
            %option{:value => "1"} Amarilla
            %option{:value => "2"} Blanca
            %option{:value => "3"} Roja
            %option{:value => "3"} Azul
          %input#last_name.validate{:placeholder => "2", :type => "text"}/

app/views/matches/edit.html.haml
%h4 Editar campeoanto

= render partial: "form"

app/views/matches/new.html.haml
.container
  %h5= "Agregar una fecha al campeonato "
  = render partial: "form"

app/views/matches/show.html.haml
 %h4= "Detalles del campeonato #{@championship.name}"
%p Fechas

app/views/weeks/_form.html.haml
= simple_form_for [@championship, @week] do |f|
  = f.input :name, wrapper_html: {class: 'input-field'}
  = f.input :date, as: :string, wrapper_html: {class: 'input-field'}, input_html: {class: 'datepicker'}
  = f.input :championship_id, as: :hidden
  %h5 Partidos
  #matches
    = f.simple_fields_for :matches do |match|
      = render 'match_fields', f: match
    .links
      = link_to_add_association 'Añadir partido', f, :matches


  = f.button  :submit, class: 'btn btn-primary'

:javascript
  M.AutoInit();

app/views/weeks/_match_fields.html.haml
.nested-fields.row
  .col.m5
    = f.input     :local_id, as: :select, collection: @teams.map{|team| ["#{team.name} (#{team.short_name})", team.id]}, wrapper_html: {class: 'input-field'}, include_blank: false
  .col.m5
    = f.input     :visitor_id, as: :select, collection: @teams.map{|team| ["#{team.name} (#{team.short_name})", team.id]}, wrapper_html: {class: 'input-field'}, include_blank: false
  .col.m2
    = link_to_remove_association "Quitar partido", f

  :javascript
    $('select').formSelect();

app/views/weeks/edit.html.haml
%h4 Editar campeoanto

= render partial: "form"

app/views/weeks/new.html.haml
.container
  %h5= "Agregar una fecha al campeonato #{@championship.name}"
  = render partial: "form"

app/views/weeks/show.html.haml
%h4= "Detalles del campeonato #{@championship.name}"
%p Fechas